import Link from 'next/link';

export default function UpgradePage() {
    return (
        <div className="min-h-screen bg-[var(--bg)] py-20 relative overflow-hidden flex justify-center w-full">
            {/* Background Effects */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-yellow-500/5 rounded-full blur-[120px] pointer-events-none" />

            <div className="max-w-4xl w-full z-10 px-4 flex flex-col items-center">
                {/* Header */}
                <div className="text-center mb-16 px-4">
                    <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-yellow-500/10 border border-yellow-500/20 text-yellow-500 text-xs font-semibold uppercase tracking-wider mb-6 shadow-[0_0_15px_rgba(234,179,8,0.1)]">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
                        </svg>
                        Professional Mode
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold text-[var(--text)] mb-6 tracking-tight">
                        Power up your workflow.
                    </h1>
                    <p className="text-lg text-[var(--muted)] max-w-xl mx-auto leading-relaxed">
                        Unlock advanced tools designed for power users and growing businesses. Build trust with custom branding, and save hours with smart automation.
                    </p>
                </div>

                {/* Feature Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16 w-full">
                    {/* Feature 1 */}
                    <div className="bg-[var(--bg)] border border-[var(--border)] rounded-2xl p-6 md:p-8 hover:border-yellow-500/20 hover:bg-[var(--card-hover)] transition-all group shadow-sm hover:shadow-lg">
                        <div className="h-12 w-12 rounded-xl bg-white/5 border border-[var(--border)] flex items-center justify-center text-[var(--text)] mb-6 group-hover:text-yellow-400 group-hover:bg-yellow-500/10 transition-colors shadow-inner">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                            </svg>
                        </div>
                        <h3 className="text-xl font-semibold text-[var(--text)] mb-3 tracking-tight">Professional Identity</h3>
                        <p className="text-[14px] text-[var(--muted)] leading-relaxed">
                            Upload your custom business logo, apply native branded colors, and entirely remove the "Generated by Verihub" watermark from your documents.
                        </p>
                    </div>

                    {/* Feature 2 */}
                    <div className="bg-[var(--bg)] border border-[var(--border)] rounded-2xl p-6 md:p-8 hover:border-yellow-500/20 hover:bg-[var(--card-hover)] transition-all group shadow-sm hover:shadow-lg">
                        <div className="h-12 w-12 rounded-xl bg-white/5 border border-[var(--border)] flex items-center justify-center text-[var(--text)] mb-6 group-hover:text-yellow-400 group-hover:bg-yellow-500/10 transition-colors shadow-inner">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
                            </svg>
                        </div>
                        <h3 className="text-xl font-semibold text-[var(--text)] mb-3 tracking-tight">Advanced Tools</h3>
                        <p className="text-[14px] text-[var(--muted)] leading-relaxed">
                            Automate data entry with Smart OCR scanning for uploaded receipts. Unlock smart categorization and process multiple receipts in bulk automatically.
                        </p>
                    </div>

                    {/* Feature 3 */}
                    <div className="bg-[var(--bg)] border border-[var(--border)] rounded-2xl p-6 md:p-8 hover:border-yellow-500/20 hover:bg-[var(--card-hover)] transition-all group md:col-span-2 shadow-sm hover:shadow-lg">
                        <div className="flex flex-col md:flex-row gap-8 md:items-center w-full">
                            <div className="flex-1 max-w-lg">
                                <div className="h-12 w-12 rounded-xl bg-white/5 border border-[var(--border)] flex items-center justify-center text-[var(--text)] mb-6 group-hover:text-yellow-400 group-hover:bg-yellow-500/10 transition-colors shadow-inner">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                    </svg>
                                </div>
                                <h3 className="text-xl font-semibold text-[var(--text)] mb-3 tracking-tight">Tax & Audit Confidence</h3>
                                <p className="text-[14px] text-[var(--muted)] leading-relaxed">
                                    Generate beautiful monthly visual reports. Export easily digestible, tax-ready CSV files summarizing your income and expenses to send directly to your accountant.
                                </p>
                            </div>

                            {/* Graphic Placeholder */}
                            <div className="hidden md:flex flex-1 justify-end opacity-20 group-hover:opacity-40 transition-opacity">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-32 w-32 text-[var(--text)]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={0.5} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                </svg>
                            </div>
                        </div>
                    </div>
                </div>

                {/* CTA */}
                <div className="flex flex-col items-center pt-8 border-t border-[var(--border)] w-full">
                    {/* Placeholder button, non-functional */}
                    <button className="px-8 py-4 rounded-xl font-bold text-base transition-all transform hover:-translate-y-0.5 shadow-[0_0_20px_rgba(234,179,8,0.2)] hover:shadow-[0_0_30px_rgba(234,179,8,0.4)]
                        bg-yellow-500 hover:bg-yellow-400 text-[#0B1220]">
                        Upgrade Mode (Coming Soon)
                    </button>

                    <Link href="/dashboard" className="text-sm text-[var(--muted)] mt-8 mb-4 hover:text-[var(--text)] transition-colors flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                        </svg>
                        Return to Dashboard
                    </Link>
                </div>
            </div>
        </div>
    );
}
